AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'tmp/**/*'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Metrics/MethodLength:
  Max: 25
  Exclude:
    - 'lib/action_cable/subscription_adapter/solid_mongoid.rb'

Metrics/ClassLength:
  Max: 250

Metrics/AbcSize:
  Max: 25
  Exclude:
    - 'lib/action_cable/subscription_adapter/solid_mongoid.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/action_cable/subscription_adapter/solid_mongoid.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'lib/action_cable/subscription_adapter/solid_mongoid.rb'
